version: "3"
services:
    project-service:
        build: ./
        volumes:
            - ./src:/app/src
        container_name: project-service
        restart: always
        env_file:
            - .env
        networks:
            - default
            - project-net
        ports:
            - ${PORT}:${PORT}
        depends_on:
            psql-projects:
                condition: service_healthy
        
    psql-projects:
        image: postgis/postgis
        container_name: psql-projects
        environment:
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./sql/initialize_database.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5429:5432
        networks:
            - project-net
            
networks:
    default:
        external: true
        name: my-net
    project-net:
        driver: bridge
        name: project-net
