version: "3"
services:
    project-service:
        build: ./
        volumes:
            - ./src:/app/src
        container_name: project-service
        restart: always
        env_file:
            - .env
        #ports:
        #    - ${PORT}:${PORT}
        networks:
            - my-net
        depends_on:
          - psql-projects
    psql-projects:
        image: postgis/postgis
        container_name: psql-projects
        environment:
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./sql/initialize_database.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - my-net
networks:
  my-net:
    external:
      name: my-net
